theme: jekyll-theme-minimal
logo: /docs/assets/images/movie_knn_2021-10-14_12-34.gif
title: [Gestures for Artworks Browsing]
description: [The browsing interface for a collection of painted hands, paper https://github.com/VBernasconi/GAB_project/blob/a223ff888807e80ece14384b86db62816aee8d65/docs/assets/images/IUI_Bernasconi.pdf]
